### ISSUE TITLE
Running docker image on OSX

### ISSUE THREAD

**Issue by pickledgator** [curtismuntz/bazel_examples#1]
Followed blog tutorial through docker build stage, but when I tried to run the docker image, I got this error:
```
➜  bazel_examples git:(master) docker run --rm -it bazel/deploy:hello_cpp_image
standard_init_linux.go:195: exec user process caused "exec format error"
```

A quick google says that I'm trying to run something built for a different architecture. But since the docker internally can be linux, I'm not sure what the issue is? Thoughts?

**Comment by curtismuntz** [comment]
It depends on how you built this target. If you build the target with standard build options ie: `bazel run //deploy:hello_cpp_image`, it should run just fine natively.

If you specified it to build with the rpi crosstool, all the binaries within the image will be built for an armv7 platform. Since your computer is likely not an armv7 cpu, it will report the exec format error.

**Comment by pickledgator** [comment]
Got this when running that command

```
(env) ➜  bazel_examples git:(master) bazel run //deploy:hello_cpp_image
ERROR: /Users/nic/Projects/bazel_examples/deploy/BUILD:13:1: no such package '@amd64_docker_base//image': Pull command failed: Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/var/tmp/_bazel_nic/96923dedeafcf05e04ccf051b1fec1d7/external/puller/file/puller.par/__main__.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/private/var/tmp/_bazel_nic/96923dedeafcf05e04ccf051b1fec1d7/external/puller/file/puller.par/containerregistry/client/__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/private/var/tmp/_bazel_nic/96923dedeafcf05e04ccf051b1fec1d7/external/puller/file/puller.par/containerregistry/client/docker_creds_.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location
  File "/private/var/tmp/_bazel_nic/96923dedeafcf05e04ccf051b1fec1d7/external/puller/file/puller.par/httplib2/__init__.py", line 942
    print "connect: (%s, %s) ************" % (self.host, self.port)
                                         ^
SyntaxError: invalid syntax
 (/Users/nic/Projects/milliwatson/env/bin/python /private/var/tmp/_bazel_nic/96923dedeafcf05e04ccf051b1fec1d7/external/puller/file/puller.par --directory /private/var/tmp/_bazel_nic/96923dedeafcf05e04ccf051b1fec1d7/external/amd64_docker_base/image --name index.docker.io/murtis/amd64_docker_base:latest) and referenced by '//deploy:hello_cpp_image'.
ERROR: Analysis of target '//deploy:hello_cpp_image' failed; build aborted.
INFO: Elapsed time: 6.715s
ERROR: Build failed. Not running target.
```

**Comment by pickledgator** [comment]
Cool that works. So you're just saying I can build the docker for armv7 but cant run it on osx. Ie, I can't use the docker as an emulator?

**Comment by curtismuntz** [comment]
You can, but I haven't set it up that way in this project. resin provides an excellent example of emulation here: [https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/](https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/). In the event you wanted to run an emulation session, you would just never call the `cross-build-end.sh` script.

My intent for this project was to develop locally using the standard bazel methods, and deploy to arm once you've verified that the software works as intended.
